
#Constantes puntuación
PUNTUACION_CIUDAD = 1
PUNTUACION_PUEBLO_CIUDAD = 2
PUNTUACION_ESTUDIOS = 2
PUNTUACION_MODALIDAD = 5
PUNTUACION_DEPORTES = 2
PUNTUACION_FUTBOL = 3
PUNTUACION_ANIME = 3
PUNTUACION_VIDEOJUEGOS = 3
PUNTUACION_GUSTOS_MUSICALES = 2

# Rutas
ARCHIVO_MENTORES = "data/mentores.xlsx"
ARCHIVO_MENTORIZADOS = "data/mentorizados.xlsx"
RUTA_SALIDA = "outputs/mejor_emparejamiento.xlsx"

# Config
MOSTRAR_TABLA_COMPLETA = True
GUARDAR_EXCEL = True